# load models and plot SSE graph to idendify the best K
import numpy
import sklearn
from sklearn.cluster import KMeans
from sklearn.externals import joblib
import matplotlib.pyplot as plt

SSE = []
k1 = joblib.load("k1.m")
SSE.append(k1.inertia_)
k2 = joblib.load("k2.m")
SSE.append(k2.inertia_)
k3 = joblib.load("k3.m")
SSE.append(k3.inertia_)
k4 = joblib.load("k4.m")
SSE.append(k4.inertia_)
k5 = joblib.load("k5.m")
SSE.append(k5.inertia_)
k6 = joblib.load("k6.m")
SSE.append(k6.inertia_)
k7 = joblib.load("k7.m")
SSE.append(k7.inertia_)
k8 = joblib.load("k8.m")
SSE.append(k8.inertia_)
k9 = joblib.load("k9.m")
SSE.append(k9.inertia_)
k10 = joblib.load("k10.m")
SSE.append(k10.inertia_)
k11 = joblib.load("k11.m")
SSE.append(k11.inertia_)
k12 = joblib.load("k12.m")
SSE.append(k12.inertia_)
k13 = joblib.load("k13.m")
SSE.append(k13.inertia_)
k14 = joblib.load("k14.m")
SSE.append(k14.inertia_)
k15 = joblib.load("k15.m")
SSE.append(k15.inertia_)
k16 = joblib.load("k16.m")
SSE.append(k16.inertia_)
k17 = joblib.load("k17.m")
SSE.append(k17.inertia_)
k18 = joblib.load("k18.m")
SSE.append(k18.inertia_)
k19 = joblib.load("k19.m")
SSE.append(k19.inertia_)

X = range(1,20)
plt.xlabel('k')
plt.ylabel('SSE')
plt.plot(X, SSE, 'o-')
x_ticks = numpy.arange(0,20,1)
plt.xticks(x_ticks)
plt.show()
